### ISSUE TITLE
Question on your 5 tag type implementations.

### ISSUE THREAD

**Issue by philpott** [yahoojp-marketing/gtm-template-ads-sgt#1]
Hi Yahoo Japan,

Had a couple questions with the the tags that you submitted. I was wondering what the relationship between the tags where. Looking at the technical implementation they are very similar -- using different bits of functionality from the same Javascript file (ytag.js). I was wondering if we could possibly stream line them down into 1 -- like how the Google analytics tag is shown in GTM -- or possibly 3 tags if they are grouped by business unit/major functionality -- like Google Ads display vs remarketing tags are displayed in GTM.

The primary reason behind reducing the tags defintions is so that we can ensure that the user is able to find the correct tag that they should be using.

**Comment by MarikaKagawa** [comment]
Hi philpott,
Thank you for your question.
As you said, our tags use the same Javascript file (ytag.js), but each tag has a unique function in each ad product. If we make these tags in one or three, users can be more confused.
Thank you for pointing this out for other users.
